#!/usr/bin/env bash
# ============================================================
# sync-env.sh — Split master .env into per-repo env files
# ============================================================
# Source:  /.env (meta-repo root)
# Writes:
#   repos/fillando-be/.env  ← COMMON + BACKEND sections
#   repos/fillando-fe/.env  ← COMMON + FRONTEND sections
#
# Sections are delimited by markers:
#   # === BEGIN <SECTION> ===
#   # === END <SECTION> ===
#
# Idempotent — safe to re-run.
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$ROOT/.env"

if [ ! -f "$ENV_FILE" ]; then
	echo "✗ $ENV_FILE not found."
	echo "  Copy docs/runbooks/env-template.env to .env and fill in values first."
	exit 1
fi

# Extract lines between BEGIN/END markers for a given section name.
extract_section() {
	local section="$1"
	sed -n "/^# === BEGIN ${section} ===/,/^# === END ${section} ===/{
		/^# === BEGIN ${section} ===/d
		/^# === END ${section} ===/d
		p
	}" "$ENV_FILE"
}

COMMON="$(extract_section "COMMON")"
BACKEND="$(extract_section "BACKEND")"
FRONTEND="$(extract_section "FRONTEND")"

# --- Backend ---
BE_TARGET="$ROOT/repos/fillando-be/.env"
{
	echo "# Auto-generated by scripts/sync-env.sh — do not edit manually"
	echo "# Source: meta-repo .env | $(date '+%Y-%m-%d %H:%M:%S')"
	echo ""
	[ -n "$COMMON" ] && echo "$COMMON" && echo ""
	echo "$BACKEND"
} > "$BE_TARGET"
echo "✓ Written $BE_TARGET"

# --- Frontend ---
FE_TARGET="$ROOT/repos/fillando-fe/.env"
{
	echo "# Auto-generated by scripts/sync-env.sh — do not edit manually"
	echo "# Source: meta-repo .env | $(date '+%Y-%m-%d %H:%M:%S')"
	echo ""
	[ -n "$COMMON" ] && echo "$COMMON" && echo ""
	echo "$FRONTEND"
} > "$FE_TARGET"
echo "✓ Written $FE_TARGET"

echo ""
echo "Done. Env files synced to child repos."
